### ISSUE TITLE
No launcher being created

### ISSUE THREAD

**Issue by evieluvsrainbows** [herecura/google-chrome-dev#1]
When the package is installed, there are no launchers installed whatsoever. I think putting these lines in the PKGBUILD will fix it (taken from the google-chrome-dev package in the Arch User Repository):

```
  # Launcher
  install -m755 google-chrome-$_channel.sh "$pkgdir"/usr/bin/google-chrome-$_channel
```

**Comment by BlackIkeEagle** [comment]
And the goal is?

To be able to get information from a configuration file in /etc/default/google-chrome-dev or ~/.config ?

**Comment by evieluvsrainbows** [comment]
The goal is to automatically create a launcher shortcut as the package is
unusable as there's no shortcuts created anywhere.

**Comment by evieluvsrainbows** [comment]
Nevermind. You fixed it in the last commit. Thanks!
